import { Platform, StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: '#F4FAF6' },
  page: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 22, paddingVertical: 36, overflow: 'hidden' },
  decorOne: { position: 'absolute', width: 260, height: 260, borderRadius: 130, backgroundColor: '#DDF2E3', top: -100, right: -90 },
  decorTwo: { position: 'absolute', width: 180, height: 180, borderRadius: 90, backgroundColor: '#FFF0D6', bottom: -80, left: -55 },
  brandBlock: { alignItems: 'center', marginBottom: 30 },
  logo: { width: 68, height: 68, borderRadius: 22, backgroundColor: '#176B45', alignItems: 'center', justifyContent: 'center', marginBottom: 14, transform: [{ rotate: '-3deg' }], ...Platform.select({ web: { boxShadow: '0 10px 24px rgba(23,107,69,.22)' }, default: { elevation: 5 } }) },
  logoLeaf: { color: '#C9F06B', fontSize: 25, position: 'absolute', top: 7, right: 12 },
  logoBasket: { color: '#FFFFFF', fontSize: 28, marginTop: 11 },
  brand: { color: '#123B2B', fontSize: 31, lineHeight: 38, fontWeight: '800', letterSpacing: -1 },
  tagline: { color: '#6A7E74', fontSize: 14, marginTop: 3 },
  card: { width: '100%', maxWidth: 440, backgroundColor: '#FFFFFF', borderRadius: 28, paddingHorizontal: 24, paddingVertical: 28, borderWidth: 1, borderColor: '#E2EEE6', ...Platform.select({ web: { boxShadow: '0 18px 60px rgba(18,59,43,.10)' }, default: { elevation: 4 } }) },
  title: { fontSize: 25, lineHeight: 32, fontWeight: '800', color: '#173D2D', textAlign: 'center' },
  subtitle: { fontSize: 14, color: '#718078', textAlign: 'center', marginTop: 5, marginBottom: 25 },
  label: { fontSize: 13, fontWeight: '700', color: '#314D40', marginBottom: 8 },
  input: { height: 54, borderWidth: 1, borderColor: '#D9E5DD', borderRadius: 14, paddingHorizontal: 16, fontSize: 16, color: '#173D2D', backgroundColor: '#FAFCFA', marginBottom: 18 },
  passwordWrap: { height: 54, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#D9E5DD', borderRadius: 14, backgroundColor: '#FAFCFA', paddingRight: 15 },
  passwordInput: { flex: 1, height: '100%', paddingHorizontal: 16, fontSize: 16, color: '#173D2D' },
  showText: { color: '#176B45', fontSize: 13, fontWeight: '800' },
  button: { height: 55, borderRadius: 15, backgroundColor: '#176B45', alignItems: 'center', justifyContent: 'center', marginTop: 24 },
  buttonPressed: { transform: [{ scale: 0.99 }], opacity: 0.92 },
  buttonDisabled: { opacity: 0.7 },
  buttonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800', letterSpacing: 0.2 },
  secureRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 18 },
  lock: { color: '#80B59A', fontSize: 8, marginRight: 7 },
  secureText: { color: '#86938C', fontSize: 12 },
  footer: { color: '#779086', fontSize: 12, marginTop: 25 },
});
